directories:
  output: release
  buildResources: build
appId: com.prairiebob.editor
productName: PrairieBob
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
extraResources:
  - from: public/tilesets
    to: tilesets
  - from: samples
    to: samples
  - from: pbob_icon_pack
    to: pbob_icon_pack
win:
  target:
    - nsis
    - portable
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
portable:
  artifactName: ${productName}-Portable-${version}.exe
electronVersion: 36.5.0
